### ISSUE TITLE
Can you give a sample .env file format with dummy data?

### ISSUE THREAD

**Issue by jrmoreau** [miguelmota/twitter-purge#1]
after cloning locally, I am unsure what my next step is. Do I just need to create a .env file? If so, how should the code be formatted? I tried several variations, but had no luck gaining access with my twitter dev creds. 

Does any other file need to be modified before running the program?

Thank you for making this helpful program!

**Comment by miguelmota** [comment]
@jrmoreau yea sorry the instructions weren't clear; create a `.env` file in the same directory. The .env file contents should look like the following, just replace the values with your actual twitter api credentials  found in the twitter [apps page](https://developer.twitter.com/en/apps).

```
TWITTER_CONSUMER_KEY="aaaaaaaaaaaaaaaaaaaaaaaaa"
TWITTER_CONSUMER_SECRET="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
TWITTER_ACCESS_TOKEN_KEY="cccccccccccccccccccccccccccccccccccccccccccccccccc"
TWITTER_ACCESS_TOKEN_SECRET="ddddddddddddddddddddddddddddddddddddddddddddd"

```

I've add a `.env.sample` to the repo. If the credentials are correct and the dependency gems are installed then nothing else is required; running the script should work.

**Comment by jrmoreau** [comment]
Thank you! Going to try again.
